<a href="https://colab.research.google.com/github/Akashkumar12/AI-ML/blob/main/U1_MH1_Data_Munging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing

In [1]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

    1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20

In [2]:
# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

Data downloaded successfully

In [3]:
!ls

B15_Data_Munging.zip
Districtwise_Basicdata.csv
Districtwise_Enrollment_details_indicator.csv
Districtwise_Teacher_indicator.csv
sample_data

## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv

In [4]:
# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

In [5]:
# YOUR CODE HERE for loading and exploring the datasets

Districtwise_Basicdata = pd.read_csv("/content/Districtwise_Basicdata.csv",skiprows=1)
Districtwise_Teacher_indicator = pd.read_csv("/content/Districtwise_Teacher_indicator.csv",skiprows=3)

In [6]:
Districtwise_Basicdata.columns = Districtwise_Basicdata.columns.str.lower()
Districtwise_Basicdata.columns.to_list()

['year',
 'statecd',
 'statename',
 'distcd',
 'distname',
 'blocks',
 'clusters',
 'villages',
 'totschools',
 'totpopulation',
 'p_06_pop',
 'p_urb_pop',
 'sexratio',
 'sexratio_06',
 'growthrate',
 'p_sc_pop',
 'p_st_pop',
 'overall_lit',
 'female_lit']

In [7]:
Districtwise_Teacher_indicator.columns = Districtwise_Teacher_indicator.columns.str.lower()
Districtwise_Teacher_indicator.columns.to_list()

['statecd',
 'statename',
 'distcd',
 'distname',
 'ac_year',
 'tch_govt1',
 'tch_govt2',
 'tch_govt3',
 'tch_govt4',
 'tch_govt5',
 'tch_govt6',
 'tch_govt7',
 'tch_govt9',
 'tch_pvt1',
 'tch_pvt2',
 'tch_pvt3',
 'tch_pvt4',
 'tch_pvt5',
 'tch_pvt6',
 'tch_pvt7',
 'tch_pvt9',
 'tch_un1',
 'tch_un2',
 'tch_un3',
 'tch_un4',
 'tch_un5',
 'tch_un6',
 'tch_un7',
 'tch_un9',
 'tch_bs1',
 'tch_bs2',
 'tch_bs3',
 'tch_bs4',
 'tch_bs5',
 'tch_bs6',
 'tch_bs7',
 'tch_bs_p',
 'tch_s1',
 'tch_s2',
 'tch_s3',
 'tch_s4',
 'tch_s5',
 'tch_s6',
 'tch_s7',
 'tch_s_p',
 'tch_hs1',
 'tch_hs2',
 'tch_hs3',
 'tch_hs4',
 'tch_hs5',
 'tch_hs6',
 'tch_hs7',
 'tch_hs_p',
 'tch_grad1',
 'tch_grad2',
 'tch_grad3',
 'tch_grad4',
 'tch_grad5',
 'tch_grad6',
 'tch_grad7',
 'tch_grad_p',
 'tch_pgrad1',
 'tch_pgrad2',
 'tch_pgrad3',
 'tch_pgrad4',
 'tch_pgrad5',
 'tch_pgrad6',
 'tch_pgrad7',
 'tch_pgrad_p',
 'tch_mph1',
 'tch_mph2',
 'tch_mph3',
 'tch_mph4',
 'tch_mph5',
 'tch_mph6',
 'tch_mph7',
 'tch_mph_p',
 'tch_pd1',
 'tch_pd2',
 'tch_pd3',
 'tch_pd4',
 'tch_pd5',
 'tch_pd6',
 'tch_pd7',
 'tch_pd_p',
 'tch_eduqual_nr1',
 'tch_eduqual_nr2',
 'tch_eduqual_nr3',
 'tch_eduqual_nr4',
 'tch_eduqual_nr5',
 'tch_eduqual_nr6',
 'tch_eduqual_nr7',
 'tch_eduqual_nr_p',
 'tch_m1',
 'tch_m2',
 'tch_m3',
 'tch_m4',
 'tch_m5',
 'tch_m6',
 'tch_m7',
 'tch_f1',
 'tch_f2',
 'tch_f3',
 'tch_f4',
 'tch_f5',
 'tch_f6',
 'tch_f7',
 'tch_nr1',
 'tch_nr2',
 'tch_nr3',
 'tch_nr4',
 'tch_nr5',
 'tch_nr6',
 'tch_nr7',
 'tch_m_p1',
 'tch_m_p2',
 'tch_m_p3',
 'tch_m_p4',
 'tch_m_p5',
 'tch_m_p6',
 'tch_m_p7',
 'tch_f_p1',
 'tch_f_p2',
 'tch_f_p3',
 'tch_f_p4',
 'tch_f_p5',
 'tch_f_p6',
 'tch_f_p7',
 'tch_nr_p1',
 'tch_nr_p2',
 'tch_nr_p3',
 'tch_nr_p4',
 'tch_nr_p5',
 'tch_nr_p6',
 'tch_nr_p7',
 'tch_sc_m1',
 'tch_sc_m2',
 'tch_sc_m3',
 'tch_sc_m4',
 'tch_sc_m5',
 'tch_sc_m6',
 'tch_sc_m7',
 'tch_sc_f1',
 'tch_sc_f2',
 'tch_sc_f3',
 'tch_sc_f4',
 'tch_sc_f5',
 'tch_sc_f6',
 'tch_sc_f7',
 'tch_st_m1',
 'tch_st_m2',
 'tch_st_m3',
 'tch_st_m4',
 'tch_st_m5',
 'tch_st_m6',
 'tch_st_m7',
 'tch_st_f1',
 'tch_st_f2',
 'tch_st_f3',
 'tch_st_f4',
 'tch_st_f5',
 'tch_st_f6',
 'tch_st_f7',
 'trn_tch_m1',
 'trn_tch_m2',
 'trn_tch_m3',
 'trn_tch_m4',
 'trn_tch_m5',
 'trn_tch_m6',
 'trn_tch_m7',
 'trn_tch_f1',
 'trn_tch_f2',
 'trn_tch_f3',
 'trn_tch_f4',
 'trn_tch_f5',
 'trn_tch_f6',
 'trn_tch_f7',
 'prof_trn_tch_r',
 'prof_trn_tch_p',
 'days_nontch',
 'tch_nontch']

In [8]:

Districtwise_Basicdata.isna().sum()

# Districtwise_Basicdata = Districtwise_Basicdata.dropna()
# Districtwise_Basicdata.isna().sum()

year              0
statecd           0
statename         0
distcd            0
distname          0
blocks            0
clusters          0
villages          0
totschools        0
totpopulation    56
p_06_pop         58
p_urb_pop        62
sexratio         56
sexratio_06      58
growthrate       56
p_sc_pop         68
p_st_pop         68
overall_lit      56
female_lit       56
dtype: int64

In [9]:
Districtwise_Teacher_indicator.isna().sum()

# Districtwise_Teacher_indicator = Districtwise_Teacher_indicator.dropna()
# Districtwise_Teacher_indicator.isna().sum()

statecd           0
statename         0
distcd            0
distname          0
ac_year           0
                 ..
trn_tch_f7        0
prof_trn_tch_r    0
prof_trn_tch_p    0
days_nontch       0
tch_nontch        0
Length: 181, dtype: int64

## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

In [10]:
df1 = Districtwise_Basicdata
df2 = Districtwise_Teacher_indicator

df1['unique_id'] = df1['year'].astype(str) + '_' + df1['statecd'].astype(str) + '_' + df1['distcd'].astype(str)
df2['unique_id'] = df2['ac_year'].astype(str) + '_' + df2['statecd'].astype(str) + '_' + df2['distcd'].astype(str)

df1 = df1.set_index('unique_id')
df2 = df2.set_index('unique_id')

print("df1 head with new index:")
display(df1.head())
print("df2 head with new index:")
display(df2.head())

df3 = df1.join(df2, how='inner', lsuffix='_basic', rsuffix='_enroll')
df3.head()

df1 head with new index:

,year,statecd,statename,distcd,distname,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,overall_lit,female_lit
unique_id,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586.0,23616.05,55.89,874.0,980.0,13.97,0.00,1.72,High,84.52
2012-13_35_3503,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539.0,11651.51,2.60,925.0,975.0,-0.07,0.00,0.72,High,79.39
2012-13_35_3502,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,3,8,42,58,36819.0,4226.82,0.00,778.0,961.0,-12.48,0.00,64.28,High,70.70
2012-13_28_2801,2012-13,28,ANDHRA PRADESH ...,2801,ADILABAD ...,52,356,1576,4983,2737738.0,295675.70,27.68,1003.0,942.0,10.04,17.82,18.09,Low,51.99
2012-13_28_2822,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315.0,427114.75,28.09,977.0,927.0,12.16,14.29,3.78,Low,54.31

df2 head with new index:

,statecd,statename,distcd,distname,ac_year,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,2012-13,329,429,1097,0,127,...,176,135,0,22,103,0,2968,228,12,519
2012-13_35_3503,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,2012-13,305,285,194,95,268,...,85,40,3,28,60,0,1249,203,8,362
2012-13_35_3502,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,2012-13,110,95,56,0,135,...,29,23,0,17,46,0,430,78,20,28
2012-13_28_2801,28,ANDHRA PRADESH ...,2801,ADILABAD ...,2012-13,4749,1788,38,0,22,...,267,0,0,0,8,248,16419,845,13,263
2012-13_28_2822,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,2012-13,5797,2879,209,8,6733,...,726,0,0,591,0,3,21487,676,14,1185

,year,statecd_basic,statename_basic,distcd_basic,distname_basic,blocks,clusters,villages,totschools,totpopulation,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3,16,83,212,237586.0,...,176,135,0,22,103,0,2968,228,12,519
2012-13_35_3503,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3,13,76,181,105539.0,...,85,40,3,28,60,0,1249,203,8,362
2012-13_35_3502,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,3,8,42,58,36819.0,...,29,23,0,17,46,0,430,78,20,28
2012-13_28_2801,2012-13,28,ANDHRA PRADESH ...,2801,ADILABAD ...,52,356,1576,4983,2737738.0,...,267,0,0,0,8,248,16419,845,13,263
2012-13_28_2822,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315.0,...,726,0,0,591,0,3,21487,676,14,1185

In [11]:
df3.columns.to_list()

['year',
 'statecd_basic',
 'statename_basic',
 'distcd_basic',
 'distname_basic',
 'blocks',
 'clusters',
 'villages',
 'totschools',
 'totpopulation',
 'p_06_pop',
 'p_urb_pop',
 'sexratio',
 'sexratio_06',
 'growthrate',
 'p_sc_pop',
 'p_st_pop',
 'overall_lit',
 'female_lit',
 'statecd_enroll',
 'statename_enroll',
 'distcd_enroll',
 'distname_enroll',
 'ac_year',
 'tch_govt1',
 'tch_govt2',
 'tch_govt3',
 'tch_govt4',
 'tch_govt5',
 'tch_govt6',
 'tch_govt7',
 'tch_govt9',
 'tch_pvt1',
 'tch_pvt2',
 'tch_pvt3',
 'tch_pvt4',
 'tch_pvt5',
 'tch_pvt6',
 'tch_pvt7',
 'tch_pvt9',
 'tch_un1',
 'tch_un2',
 'tch_un3',
 'tch_un4',
 'tch_un5',
 'tch_un6',
 'tch_un7',
 'tch_un9',
 'tch_bs1',
 'tch_bs2',
 'tch_bs3',
 'tch_bs4',
 'tch_bs5',
 'tch_bs6',
 'tch_bs7',
 'tch_bs_p',
 'tch_s1',
 'tch_s2',
 'tch_s3',
 'tch_s4',
 'tch_s5',
 'tch_s6',
 'tch_s7',
 'tch_s_p',
 'tch_hs1',
 'tch_hs2',
 'tch_hs3',
 'tch_hs4',
 'tch_hs5',
 'tch_hs6',
 'tch_hs7',
 'tch_hs_p',
 'tch_grad1',
 'tch_grad2',
 'tch_grad3',
 'tch_grad4',
 'tch_grad5',
 'tch_grad6',
 'tch_grad7',
 'tch_grad_p',
 'tch_pgrad1',
 'tch_pgrad2',
 'tch_pgrad3',
 'tch_pgrad4',
 'tch_pgrad5',
 'tch_pgrad6',
 'tch_pgrad7',
 'tch_pgrad_p',
 'tch_mph1',
 'tch_mph2',
 'tch_mph3',
 'tch_mph4',
 'tch_mph5',
 'tch_mph6',
 'tch_mph7',
 'tch_mph_p',
 'tch_pd1',
 'tch_pd2',
 'tch_pd3',
 'tch_pd4',
 'tch_pd5',
 'tch_pd6',
 'tch_pd7',
 'tch_pd_p',
 'tch_eduqual_nr1',
 'tch_eduqual_nr2',
 'tch_eduqual_nr3',
 'tch_eduqual_nr4',
 'tch_eduqual_nr5',
 'tch_eduqual_nr6',
 'tch_eduqual_nr7',
 'tch_eduqual_nr_p',
 'tch_m1',
 'tch_m2',
 'tch_m3',
 'tch_m4',
 'tch_m5',
 'tch_m6',
 'tch_m7',
 'tch_f1',
 'tch_f2',
 'tch_f3',
 'tch_f4',
 'tch_f5',
 'tch_f6',
 'tch_f7',
 'tch_nr1',
 'tch_nr2',
 'tch_nr3',
 'tch_nr4',
 'tch_nr5',
 'tch_nr6',
 'tch_nr7',
 'tch_m_p1',
 'tch_m_p2',
 'tch_m_p3',
 'tch_m_p4',
 'tch_m_p5',
 'tch_m_p6',
 'tch_m_p7',
 'tch_f_p1',
 'tch_f_p2',
 'tch_f_p3',
 'tch_f_p4',
 'tch_f_p5',
 'tch_f_p6',
 'tch_f_p7',
 'tch_nr_p1',
 'tch_nr_p2',
 'tch_nr_p3',
 'tch_nr_p4',
 'tch_nr_p5',
 'tch_nr_p6',
 'tch_nr_p7',
 'tch_sc_m1',
 'tch_sc_m2',
 'tch_sc_m3',
 'tch_sc_m4',
 'tch_sc_m5',
 'tch_sc_m6',
 'tch_sc_m7',
 'tch_sc_f1',
 'tch_sc_f2',
 'tch_sc_f3',
 'tch_sc_f4',
 'tch_sc_f5',
 'tch_sc_f6',
 'tch_sc_f7',
 'tch_st_m1',
 'tch_st_m2',
 'tch_st_m3',
 'tch_st_m4',
 'tch_st_m5',
 'tch_st_m6',
 'tch_st_m7',
 'tch_st_f1',
 'tch_st_f2',
 'tch_st_f3',
 'tch_st_f4',
 'tch_st_f5',
 'tch_st_f6',
 'tch_st_f7',
 'trn_tch_m1',
 'trn_tch_m2',
 'trn_tch_m3',
 'trn_tch_m4',
 'trn_tch_m5',
 'trn_tch_m6',
 'trn_tch_m7',
 'trn_tch_f1',
 'trn_tch_f2',
 'trn_tch_f3',
 'trn_tch_f4',
 'trn_tch_f5',
 'trn_tch_f6',
 'trn_tch_f7',
 'prof_trn_tch_r',
 'prof_trn_tch_p',
 'days_nontch',
 'tch_nontch']

In [12]:
df1.shape

(1324, 19)

In [13]:
df2.shape

(1324, 181)

In [14]:
df3.shape

(1324, 200)

In [15]:

df1[df1["distname"].str.contains("ANANTAPUR")]

,year,statecd,statename,distcd,distname,blocks,clusters,villages,totschools,totpopulation,p_06_pop,p_urb_pop,sexratio,sexratio_06,growthrate,p_sc_pop,p_st_pop,overall_lit,female_lit
unique_id,,,,,,,,,,,,,,,,,,,
2012-13_28_2822,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315.0,427114.75,28.09,977.0,927.0,12.16,14.29,3.78,Low,54.31
2013-14_28_2822,2013-14,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,550,918,5065,4083315.0,427114.75,28.09,977.0,927.0,12.16,14.29,3.78,Low,54.31

In [16]:
df2[df2["distname"].str.contains("ANANTAPUR")]

,statecd,statename,distcd,distname,ac_year,tch_govt1,tch_govt2,tch_govt3,tch_govt4,tch_govt5,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_28_2822,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,2012-13,5797,2879,209,8,6733,...,726,0,0,591,0,3,21487,676,14,1185
2013-14_28_2822,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,2013-14,6139,2907,101,0,204,...,487,1,0,0,0,259,23268,739,14,1086

In [17]:
df3[df3["distname_basic"].str.contains("ANANTAPUR")]

,year,statecd_basic,statename_basic,distcd_basic,distname_basic,blocks,clusters,villages,totschools,totpopulation,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_28_2822,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315.0,...,726,0,0,591,0,3,21487,676,14,1185
2013-14_28_2822,2013-14,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,550,918,5065,4083315.0,...,487,1,0,0,0,259,23268,739,14,1086

In [18]:
df3[df3["distname_enroll"].str.contains("ANANTAPUR")]

,year,statecd_basic,statename_basic,distcd_basic,distname_basic,blocks,clusters,villages,totschools,totpopulation,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_28_2822,2012-13,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,564,929,5188,4083315.0,...,726,0,0,591,0,3,21487,676,14,1185
2013-14_28_2822,2013-14,28,ANDHRA PRADESH ...,2822,ANANTAPUR ...,63,550,918,5065,4083315.0,...,487,1,0,0,0,259,23268,739,14,1086

## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values

In [19]:

df3["overall_lit"].isna().sum()

np.int64(56)

In [20]:
df3["overall_lit"].dropna(inplace=True)

In [21]:
df3.shape

(1324, 200)

In [22]:
print(f"Missing values in 'overall_lit' column before dropping: {df3['overall_lit'].isnull().sum()}")
print(f"Current DataFrame shape before dropping: {df3.shape}")

df3.dropna(subset=['overall_lit'], inplace=True)

print(f"\nMissing values in 'overall_lit' column after dropping: {df3['overall_lit'].isnull().sum()}")
print(f"New DataFrame shape after dropping: {df3.shape}")

Missing values in 'overall_lit' column before dropping: 56
Current DataFrame shape before dropping: (1324, 200)

Missing values in 'overall_lit' column after dropping: 0
New DataFrame shape after dropping: (1268, 200)

In [23]:
# YOUR CODE HERE for data cleaning

categorical_cols = df3.select_dtypes(include=['object']).columns.tolist()
categorical_cols

['year',
 'statename_basic',
 'distname_basic',
 'overall_lit',
 'statename_enroll',
 'distname_enroll',
 'ac_year']

In [24]:
import sklearn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

print(f"Categorical columns ({len(categorical_cols)}): {categorical_cols[:10]}")
# Apply LabelEncoder to each categorical column
for col in categorical_cols:
    df3[col] = le.fit_transform(df3[col].astype(str))

Categorical columns (7): ['year', 'statename_basic', 'distname_basic', 'overall_lit', 'statename_enroll', 'distname_enroll', 'ac_year']

In [25]:
# df3['year', 'statename_basic', 'distname_basic', 'overall_lit', 'statename_enroll', 'distname_enroll', 'ac_year']
print(df3.dtypes.value_counts())
df3.head()

df3[['year', 'statename_basic', 'distname_basic', 'overall_lit', 'statename_enroll', 'distname_enroll', 'ac_year']].head()
# df_merged[['district', 'state', 'overall_lit']].head()
# df3['year'].unique()

int64      191
float64      9
Name: count, dtype: int64

,year,statename_basic,distname_basic,overall_lit,statename_enroll,distname_enroll,ac_year
unique_id,,,,,,,
2012-13_35_3501,0,0,21,0,0,21,0
2012-13_35_3503,0,0,382,0,0,382,0
2012-13_35_3502,0,0,422,0,0,422,0
2012-13_28_2801,0,1,0,1,1,0,0
2012-13_28_2822,0,1,19,1,1,19,0

In [26]:
print(f"Missing values before filling: {df3.isnull().sum().sum()}")
# Fill missing values with the mean of each column
df3 = df3.fillna(df3.mean())
print(f"Missing values after filling: {df3.isnull().sum().sum()}")
print(f"\nDataFrame shape: {df3.shape}")

Missing values before filling: 34
Missing values after filling: 0

DataFrame shape: (1268, 200)

## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.

In [27]:
# YOUR CODE HERE for cleaning the dataframe
df3.columns.to_list()
df3[['statename_basic','statecd_basic','distcd_basic','distname_basic']]

                 statename_basic  statecd_basic  distcd_basic  distname_basic
unique_id
2012-13_35_3501                0             35          3501              21
2012-13_35_3503                0             35          3503             382
2012-13_35_3502                0             35          3502             422
2012-13_28_2801                1             28          2801               0
2012-13_28_2822                1             28          2822              19
...                          ...            ...           ...             ...
2013-14_19_1919               36             19          1919             466
2013-14_19_1914               36             19          1914             470
2013-14_19_1921               36             19          1921             536
2013-14_19_1918               36             19          1918             553
2013-14_19_1904               36             19          1904             605

[1268 rows x 4 columns]

In [28]:
columns_to_drop = [
    'statecd_enroll',
    'statename_enroll',
    'distcd_enroll',
    'distname_enroll',
    'ac_year'
]

df3 = df3.drop(columns=columns_to_drop)

print(f"New DataFrame shape after dropping duplicate identifier columns: {df3.shape}")
display(df3.head())

New DataFrame shape after dropping duplicate identifier columns: (1268, 195)

,year,statecd_basic,statename_basic,distcd_basic,distname_basic,blocks,clusters,villages,totschools,totpopulation,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,0,35,0,3501,21,3,16,83,212,237586.0,...,176,135,0,22,103,0,2968,228,12,519
2012-13_35_3503,0,35,0,3503,382,3,13,76,181,105539.0,...,85,40,3,28,60,0,1249,203,8,362
2012-13_35_3502,0,35,0,3502,422,3,8,42,58,36819.0,...,29,23,0,17,46,0,430,78,20,28
2012-13_28_2801,0,28,1,2801,0,52,356,1576,4983,2737738.0,...,267,0,0,0,8,248,16419,845,13,263
2012-13_28_2822,0,28,1,2822,19,63,564,929,5188,4083315.0,...,726,0,0,591,0,3,21487,676,14,1185

In [29]:
df3.isna().sum()

year               0
statecd_basic      0
statename_basic    0
distcd_basic       0
distname_basic     0
                  ..
trn_tch_f7         0
prof_trn_tch_r     0
prof_trn_tch_p     0
days_nontch        0
tch_nontch         0
Length: 195, dtype: int64

## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.

In [30]:
def remove_Highly_Correlated(df, bar=0.9):
  # Creates correlation matrix
  corr = df.corr()

  # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

In [31]:
# YOUR CODE HERE to remove highly correlated features from the dataframe by calling above function.
df4 =remove_Highly_Correlated(df3)

length of highly correlated columns 26
shape of data (1268, 195) shape of reduced data (1268, 169)

## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [32]:
df4.shape

(1268, 169)

In [33]:
# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler

In [34]:

scaler = StandardScaler()
numerical_cols = df4.select_dtypes(include=np.number).columns.tolist()

numerical_cols

['year',
 'statename_basic',
 'distcd_basic',
 'distname_basic',
 'blocks',
 'clusters',
 'villages',
 'totschools',
 'p_06_pop',
 'p_urb_pop',
 'sexratio',
 'sexratio_06',
 'growthrate',
 'p_sc_pop',
 'p_st_pop',
 'overall_lit',
 'female_lit',
 'tch_govt2',
 'tch_govt3',
 'tch_govt6',
 'tch_govt9',
 'tch_pvt1',
 'tch_pvt2',
 'tch_pvt4',
 'tch_pvt5',
 'tch_pvt9',
 'tch_un1',
 'tch_un2',
 'tch_un3',
 'tch_un4',
 'tch_un5',
 'tch_un6',
 'tch_un7',
 'tch_un9',
 'tch_bs1',
 'tch_bs2',
 'tch_bs3',
 'tch_bs4',
 'tch_bs5',
 'tch_bs6',
 'tch_bs7',
 'tch_bs_p',
 'tch_s1',
 'tch_s2',
 'tch_s3',
 'tch_s4',
 'tch_s5',
 'tch_s6',
 'tch_s_p',
 'tch_hs1',
 'tch_hs2',
 'tch_hs3',
 'tch_hs4',
 'tch_hs5',
 'tch_hs6',
 'tch_hs7',
 'tch_hs_p',
 'tch_grad1',
 'tch_grad2',
 'tch_grad_p',
 'tch_pgrad1',
 'tch_pgrad2',
 'tch_pgrad4',
 'tch_pgrad6',
 'tch_pgrad_p',
 'tch_mph1',
 'tch_mph2',
 'tch_mph4',
 'tch_mph5',
 'tch_mph6',
 'tch_mph7',
 'tch_mph_p',
 'tch_pd1',
 'tch_pd2',
 'tch_pd3',
 'tch_pd4',
 'tch_pd5',
 'tch_pd6',
 'tch_pd7',
 'tch_pd_p',
 'tch_eduqual_nr1',
 'tch_eduqual_nr2',
 'tch_eduqual_nr3',
 'tch_eduqual_nr4',
 'tch_eduqual_nr5',
 'tch_eduqual_nr6',
 'tch_eduqual_nr7',
 'tch_eduqual_nr_p',
 'tch_m1',
 'tch_m4',
 'tch_f1',
 'tch_f2',
 'tch_f3',
 'tch_f4',
 'tch_f5',
 'tch_f6',
 'tch_f7',
 'tch_nr1',
 'tch_nr2',
 'tch_nr3',
 'tch_nr4',
 'tch_nr5',
 'tch_nr6',
 'tch_nr7',
 'tch_m_p1',
 'tch_m_p2',
 'tch_m_p3',
 'tch_m_p6',
 'tch_m_p7',
 'tch_f_p1',
 'tch_f_p2',
 'tch_f_p3',
 'tch_f_p4',
 'tch_f_p5',
 'tch_f_p6',
 'tch_f_p7',
 'tch_nr_p1',
 'tch_nr_p2',
 'tch_nr_p3',
 'tch_nr_p4',
 'tch_nr_p5',
 'tch_nr_p6',
 'tch_nr_p7',
 'tch_sc_m1',
 'tch_sc_m2',
 'tch_sc_m3',
 'tch_sc_m4',
 'tch_sc_m5',
 'tch_sc_m6',
 'tch_sc_m7',
 'tch_sc_f1',
 'tch_sc_f2',
 'tch_sc_f3',
 'tch_sc_f4',
 'tch_sc_f5',
 'tch_sc_f6',
 'tch_sc_f7',
 'tch_st_m1',
 'tch_st_m2',
 'tch_st_m3',
 'tch_st_m4',
 'tch_st_m5',
 'tch_st_m6',
 'tch_st_m7',
 'tch_st_f1',
 'tch_st_f2',
 'tch_st_f3',
 'tch_st_f4',
 'tch_st_f5',
 'tch_st_f6',
 'tch_st_f7',
 'trn_tch_m1',
 'trn_tch_m2',
 'trn_tch_m3',
 'trn_tch_m4',
 'trn_tch_m5',
 'trn_tch_m6',
 'trn_tch_m7',
 'trn_tch_f1',
 'trn_tch_f2',
 'trn_tch_f3',
 'trn_tch_f4',
 'trn_tch_f5',
 'trn_tch_f6',
 'trn_tch_f7',
 'prof_trn_tch_r',
 'prof_trn_tch_p',
 'days_nontch',
 'tch_nontch']

In [35]:

df4[numerical_cols] = scaler.fit_transform(df4[numerical_cols])

display(df4.head())

,year,statename_basic,distcd_basic,distname_basic,blocks,clusters,villages,totschools,p_06_pop,p_urb_pop,...,trn_tch_f2,trn_tch_f3,trn_tch_f4,trn_tch_f5,trn_tch_f6,trn_tch_f7,prof_trn_tch_r,prof_trn_tch_p,days_nontch,tch_nontch
unique_id,,,,,,,,,,,,,,,,,,,,,
2012-13_35_3501,-1.0,-1.782918,1.894217,-1.614493,-0.828445,-1.109180,-1.307226,-1.375512,-1.139733,1.632431,...,-0.292820,0.514248,-0.494098,-0.292423,1.274906,-0.377127,-0.785267,-0.293687,-0.359209,0.047086
2012-13_35_3503,-1.0,-1.782918,1.896343,0.350153,-0.828445,-1.138707,-1.318262,-1.396885,-1.199653,-1.167381,...,-0.395004,0.038853,-0.470878,-0.264741,0.625907,-0.377127,-1.026722,-0.329009,-0.618519,-0.089579
2012-13_35_3502,-1.0,-1.782918,1.895280,0.567842,-0.828445,-1.187918,-1.371868,-1.481690,-1.236838,-1.303983,...,-0.457886,-0.046217,-0.494098,-0.315492,0.414605,-0.377127,-1.141760,-0.505620,0.159410,-0.380319
2012-13_28_2801,-1.0,-1.692158,1.149962,-1.728780,4.173296,2.237191,1.046709,1.913955,0.222788,0.150301,...,-0.190636,-0.161313,-0.494098,-0.393926,-0.158929,1.903111,1.104093,0.578065,-0.294382,-0.175757
2012-13_28_2822,-1.0,-1.692158,1.172289,-1.625377,5.296136,4.284383,0.026618,2.055296,0.881057,0.171842,...,0.324775,-0.161313,-0.494098,2.332798,-0.279673,-0.349544,1.815956,0.339287,-0.229554,0.626826

## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%

In [36]:
# YOUR CODE HERE for applying different classifiers
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

y= df4["overall_lit"]
X = df4.drop("overall_lit", axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
lr  = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [38]:
y_predict = lr.predict(X_test)

In [39]:
lr.score(X_train,y_train)

0.5191083451409453

In [40]:
lr.score(X_test,y_test)

0.13431047206085156

In [41]:
from sklearn.tree import DecisionTreeClassifier

unique_y_values = sorted(y_train.unique())
y_mapping = {val: i for i, val in enumerate(unique_y_values)}

y_train_discrete = y_train.map(y_mapping)
y_test_discrete = y_test.map(y_mapping)

dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train_discrete)

print(f"Decision Tree Classifier Training Accuracy: {dt_classifier.score(X_train, y_train_discrete)}")
print(f"Decision Tree Classifier Test Accuracy: {dt_classifier.score(X_test, y_test_discrete)}")

Decision Tree Classifier Training Accuracy: 1.0
Decision Tree Classifier Test Accuracy: 0.937007874015748

In [42]:
from sklearn.linear_model import LogisticRegression

log_reg_model = LogisticRegression(random_state=42, max_iter=1000) # Increased max_iter for convergence
log_reg_model.fit(X_train, y_train_discrete)

print(f"Logistic Regression Training Accuracy: {log_reg_model.score(X_train, y_train_discrete)}")
print(f"Logistic Regression Test Accuracy: {log_reg_model.score(X_test, y_test_discrete)}")

Logistic Regression Training Accuracy: 0.9812623274161736
Logistic Regression Test Accuracy: 0.8661417322834646

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(random_state=42, n_estimators=100) # Using 100 estimators as a default
rf_classifier.fit(X_train, y_train_discrete)

print(f"Random Forest Classifier Training Accuracy: {rf_classifier.score(X_train, y_train_discrete)}")
print(f"Random Forest Classifier Test Accuracy: {rf_classifier.score(X_test, y_test_discrete)}")

Random Forest Classifier Training Accuracy: 1.0
Random Forest Classifier Test Accuracy: 0.9094488188976378